### ISSUE TITLE
input-fields are on default size after reopening popup

### ISSUE THREAD

**Issue by smn57** [smn57/frag.extract.a#5]
When editing a fragment in popup, closing it and reopening it again all input fields are on default size. Which means even with a lot of context in a field only one line is shown. 
![Auswahl_141](https://user-images.githubusercontent.com/34234300/61278445-83e0a400-a7b4-11e9-8c20-495837996875.png)

**Comment by smn57** [comment]
Code field has bigger size now.
Spacing reduced and font-size reduced.

**Comment by tneuschaefer** [comment]
Description also has a bigger size now. This should prevent content not being shown for almost all cases and in cases where the description or the codeblock are so long, that they don't fit in their input fields it is not useful to show them full length anyway, because the popup is restricted in size
